addReviewers: true
addAssignees: author

# Set this to the length of the reviewers list because the default was not including everyone
numberOfReviewers: 4

reviewers:
  - nrb
  - ashish-amarnath
  - carlisia
  - zubron
